// <auto-generated />
using DowntimeAlerterWeb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DowntimeAlerterWeb.Migrations.DowntimeAlerterData
{
    [DbContext(typeof(DowntimeAlerterDataContext))]
    [Migration("20210227100338_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");
#pragma warning restore 612, 618
        }
    }
}
